name: Auto Deploy to AWS EC2
run-name: ${{ github.repository }} is automatic deploy to AWS EC2 🚀

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      # - name: Build
      #   run: npm run build

      - name: Configure SSH
        run: |
          echo "remore setup ssh"
          # mkdir -p ~/.ssh
          # echo "$secrets.SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        run: |
          echo "Deploying to AWS EC2"
          # scp -r ./dist ubuntu@${{ secrets.HOST }}:/path/to/your/app
          # ssh ubuntu@${{ secrets.HOST }} 'cd /path/to/your/app && npm install && pm2 restart your-app'
